fastlane_version "2.35.1"

default_platform :android

platform :android do
  RELEASE_APK_PATH = 'app/build/outputs/apk/release/app-release.apk'

  desc "Deploy a new version to the Google Play - BETA"
  lane :beta do
    cleanBuild
    createReleaseBuild
    pushToBeta
  end

  desc "Clean project"
  lane :cleanBuild do
    #Clean the build
    gradle(task: 'clean')
  end

  desc "Create release build"
  lane :createReleaseBuild do
    #Create release build
    gradle(task: 'assemble', build_type: 'Release')
  end

  desc "Push apk to beta, skip uploading metadata, images and screenshots."
  lane :pushToBeta do
    #Push the apk on beta
    #Set 'skip_upload_m.etadata' to true to skip uploading metadata
    #Set 'skip_upload_images' to true to skip uploading images
    #Set 'skip_upload_screenshots' to true to skip uploading screenshots

    supply(
        track: 'beta',
        apk: RELEASE_APK_PATH,
        skip_upload_metadata: 'true',
        skip_upload_images: 'true',
        skip_upload_screenshots: 'true')
  end
end
